version: '2.2'
services:

  frontend:
    container_name: frontend
    image:  ilyukou/frontend:0.1
    ports:
      - '3000:3000'
      - '3001:3001'
#
  mongo:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=iot
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017-27019:27017-27019"

  api:
    image: ilyukou/api:0.1
    container_name: api
    command: -timeout 60s
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Minsk
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.21
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
      - "33060:33060"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iot
      MYSQL_USER: iot
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    ports:
        - "9200:9200"
        - "9300:9300"
    restart: always
    environment:
      discovery.type: single-node
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5

  activemq:
    image: rmohr/activemq:5.15.6
    container_name: activemq
    ports:
      - "61616:61616"
      - "8162:8162"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:61617" ]
      interval: 30s
      timeout: 10s
      retries: 5